### ISSUE TITLE
Setup Level manager

### ISSUE THREAD

**Issue by joelgb2194** [AttainableEntertainment/Project_1#24]
- Initial spawn location 
- Hazard collision, death on touch,
- Death animation
- Quick Screen transition
- Reload scene state

**Comment by jonreis90** [comment]
I like breaking the tasks into smaller specific portions, these are a mix of tasks me and chris will be working on individually

**Comment by joelgb2194** [comment]
Yep that's legit. Was mostly putting this in because I knew you guys were
already working on it and just wanted to test out an issue for the project
board to see how quick it is to manage
