### ISSUE TITLE
Save/Load System

### ISSUE THREAD

**Issue by ChrisLGit** [AttainableEntertainment/Project_1#9]
If player gets to certain areas, they can restart the level or at a transform location established in the level. Volume

**Comment by jonreis90** [comment]
No longer need probably, closing it for now

**Comment by ChrisLGit** [comment]
Changed from Checkpoint system to Save and Load system. 
-Used when player presses Start Game in the main menu to find out last chapter, player position in the level map and which levels are locked or not. 
-If player beats level, it will save and update accordingly.
